version: '3.2'

volumes:
  data:

services:
  postgres:
    image: postgres:10-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./db:/usr/db
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DB}
      - SCHEMA=${PG_SCHEMA}
      - ANON=${PG_ANON}
      - JWT=${PG_JWT}
      - FUSER=${PG_FUSER}
      - INITFOLDER=/usr/db

  postgraphile:
    image: postgraphile
    restart: always
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      - USER=${PG_USER}
      - PASS=${PG_PASS}
      - HOST=postgres
      - PORT=5432
      - DB=${PG_DB}
      - SCHEMA=${PG_SCHEMA}
      - ANON=${PG_ANON}
      - JWT=${PG_JWT}
      - SECRET=${PG_SECRET}
